### ISSUE TITLE
[Suggestion] Standardize auto-linking respective libs in .modulemaps

### ISSUE THREAD

**Issue by L1ghtmann** [theos/lib#18]
What are the steps to reproduce this issue?
-------------------------------------------
N/A

What happens?
-------------
N/A

What were you expecting to happen?
----------------------------------
N/A

Any logs, error output, etc?
----------------------------

Any other comments?
-------------------
Note: I am not well versed on clang modules/module maps.

Currently, 8/9 of the module maps Theos provides auto-link their respective libraries. The only module map currently in this repo -- Alderis' -- does not and those in the soon-to-be-merged Orion [lib pr](https://github.com/theos/lib/pull/15/files) do not. This seems like something worth standardizing so that we can have consistent module usage across provided libraries/frameworks. 

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by leptos-null** [comment]
I believe this discrepancy is caused by the same underlying difference described in <https://github.com/theos/headers/issues/83>: frameworks do not need to specify the name of their binary since they are self-contained.

**Comment by L1ghtmann** [comment]
Ah, gotcha. Thanks for the clarification!
