### ISSUE TITLE
Theos has outdated cydia substrate

### ISSUE THREAD

**Issue by Razzile** [theos/lib#5]
Theos has an outdated version of substrate, in vendor/include/substrate.h and vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd

new header can be found in the deb at http://apt.saurik.com/beta/substrate11/
new .tbd file has new symbol `_MSHookMemory` (there may also be more new symbols I haven't checked)

**Comment by kirb** [comment]
The header has a comment specifically pointing out that it’s licensed under GPL for some reason and I don’t think it’s correct for Theos to be distributing it as it has non-trivial macros like MSHookIvar. More explanation in [LICENSE.md](https://github.com/theos/lib/blob/master/LICENSE.md#saurikit).

I’ll say it’s fine to update the tbd though so you just need to BYO substrate.h.

**Comment by iosdec** [comment]
This solved my problem - thank you @Razzile !

**Comment by kirb** [comment]
Fixed by #7.
