### ISSUE TITLE
CydiaSubstrate.tbd generates a warning in Theos

### ISSUE THREAD

**Issue by NSExceptional** [theos/lib#9]
```
ld: warning: building for iOS, but linking in .tbd file
    (/opt/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd)
    built for iOS Simulator
```

Contents of the file:

```
…
archs:           [ armv7, armv7s, arm64, arm64e, i386, x86_64 ]
platform:        ios
install-name:    /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate
…
```

The warning goes away when you remove the intel archs obviously, but that's no good. Why does this warning appear at all?

**Comment by kabiroberai** [comment]
This has been resolved in a feature branch, see 29edf8e3f5a6f048d8121f5c83fc80b8f348b115. Closing as there's also currently an issue open in the main Theos repo to track this: https://github.com/theos/theos/issues/456.
